set -Ux NVM_NODEJS_ORG_MIRROR "https://npmmirror.com/mirrors/node/"
set -Ux HOMEBREW_CORE_GIT_REMOTE "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
set -Ux HEX_MIRROR "https://hexpm.upyun.com"
set -Ux HEX_CDN "https://hexpm.upyun.com"
set -Ux PUB_HOSTED_URL "https://mirrors.tuna.tsinghua.edu.cn/dart-pub"
set -Ux FLUTTER_STORAGE_BASE_URL "https://mirrors.tuna.tsinghua.edu.cn/flutter"
set -Ux ANDROID_SDK_ROOT "/home/chaos/Library/Android/sdk"
set -Ux HOMEBREW_API_DOMAIN "https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
set -Ux HOMEBREW_BOTTLE_DOMAIN "https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
set -Ux HOMEBREW_BREW_GIT_REMOTE "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
set -Ux HOMEBREW_CORE_GIT_REMOTE "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
set -Ux HOMEBREW_PIP_INDEX_URL "https://pypi.tuna.tsinghua.edu.cn/simple"
set -Ux NODE_OPTIONS "--openssl-legacy-provider"
set -Ux CHROME_EXECUTABLE "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge"
#set -Ux ANDROID_HOME "/usr/local/Caskroom/android-sdk/4333796/"
set -Ux ANDROID_HOME "/Users/chaos/Library/Android/sdk/"
set -Ux JAVA_HOME "/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home"
